my:
    filePathRoot: "log_17"
    notes: "The Effect of Testing Methods in Sports Scenarios"
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath_rigid.in:  "../DeNVeR_in/xca_dataset_sub2"
    datasetPath_rigid.out:  "log_17/xca_dataset_sub2"
    datasetPath_soft.in:  "log_17/xca_dataset_sub2"
    datasetPath_soft.out:  "log_17/xca_dataset_sub2"
    datasetPath_gt:  "../DeNVeR_in/xca_dataset_sub2"
    datasetPath:  "log_17/xca_dataset_sub2"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

