my:
    filePathRoot: "log_11"
    notes: "Test how to achieve 100% recall rate without blocking cath"
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath:  "../DeNVeR_in/xca_dataset_sim2"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

