my:
    filePathRoot: "log_12"
    notes: "Testing whether improving the recall of the shielding mask can enhance the dice of fluid layer segmentation."
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath:  "../DeNVeR_in/xca_dataset_sim2"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

