my:
    filePathRoot: "log_19"
    notes: "Attempt to optimize local deformation and software separation."
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath_rigid.in:  "../DeNVeR_in/xca_dataset_sub4"
    datasetPath_rigid.out:  "log_19/xca_dataset_sub4"
    datasetPath_soft.in:  "log_19/xca_dataset_sub4"
    datasetPath_soft.out:  "log_19/xca_dataset_sub4"
    datasetPath_gt:  "../DeNVeR_in/xca_dataset_sub4"
    datasetPath:  "log_19/xca_dataset_sub4"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

