my:
    filePathRoot: "log_18"
    notes: "Attempt to solve two major difficulties"
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath_rigid.in:  "../DeNVeR_in/xca_dataset_sub3"
    datasetPath_rigid.out:  "log_18/xca_dataset_sub3"
    datasetPath_soft.in:  "log_18/xca_dataset_sub3"
    datasetPath_soft.out:  "log_18/xca_dataset_sub3"
    datasetPath_gt:  "../DeNVeR_in/xca_dataset_sub3"
    datasetPath:  "log_18/xca_dataset_sub3"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

