my:
    filePathRoot: "log_9"
    notes: "Find out the cause of the black dot in CVAI-2186RAO28_CAU28.A.rigid.main_non1.00055.png"
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath:  "../DeNVeR_in/xca_dataset_sim2"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

