my:
    filePathRoot: "log_22"
    notes: "使用经过裁剪后相同长度的视频."
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath_rigid.in:  "../DeNVeR_in/xca_dataset_sim4"
    datasetPath_rigid.out:  "log_22/xca_dataset_sim4"
    datasetPath_soft.in:  "log_22/xca_dataset_sim4"
    datasetPath_soft.out:  "log_22/xca_dataset_sim4"
    datasetPath_gt:  "../DeNVeR_in/xca_dataset_sim4"
    datasetPath:  "log_22/xca_dataset_sim4"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

