my:
    filePathRoot: "log_10"
    notes: "Remove redundant code"
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath:  "../DeNVeR_in/xca_dataset_sim2"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

