my:
    filePathRoot: "log_23"
    notes: "使用原始数据集."
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath_rigid.in:  "../DeNVeR_in/xca_dataset"
    datasetPath_rigid.out:  "log_23/xca_dataset"
    datasetPath_soft.in:  "log_23/xca_dataset"
    datasetPath_soft.out:  "log_23/xca_dataset"
    datasetPath_gt:  "../DeNVeR_in/xca_dataset"
    datasetPath:  "log_23/xca_dataset"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

