my:
    filePathRoot: "log_13"
    notes: "Demonstrating the Effectiveness of Fluid Decoupling in Long Videos."
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath:  "../DeNVeR_in/xca_dataset_sub1"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

