my:
    filePathRoot: "log_20"
    notes: "回到优化分割结果的目标上来."
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath_rigid.in:  "../DeNVeR_in/xca_dataset_sub4"
    datasetPath_rigid.out:  "log_20/xca_dataset_sub4"
    datasetPath_soft.in:  "log_20/xca_dataset_sub4"
    datasetPath_soft.out:  "log_20/xca_dataset_sub4"
    datasetPath_gt:  "../DeNVeR_in/xca_dataset_sub4"
    datasetPath:  "log_20/xca_dataset_sub4"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

