my:
    filePathRoot: "log_21"
    notes: "用于论文表格的实验."
    subPath:
        nirIn : "nir_image"
        outputs : "outputs"
    datasetPath_rigid.in:  "../DeNVeR_in/xca_dataset_sub4"
    datasetPath_rigid.out:  "log_21/xca_dataset_sub4"
    datasetPath_soft.in:  "log_21/xca_dataset_sub4"
    datasetPath_soft.out:  "log_21/xca_dataset_sub4"
    datasetPath_gt:  "../DeNVeR_in/xca_dataset_sub4"
    datasetPath:  "log_21/xca_dataset_sub4"
    raftConfig: "../DeNVeR_in/models_config"
    TestFlag: False
    useFreeCOS: True

